// AUTO-GENERATED FILE.
// This file is auto-generated by the Ballerina OpenAPI tool.

import ballerina/http;

listener http:Listener ep0 = new (9090);

service / on ep0 {
    # Get the fixed hello world greeting
    #
    # + return - returns can be any of following types
    # http:Ok (The greeting was returned successfully.)
    # http:InternalServerError (Unexpected server error.)
    resource function get hello() returns Greeting|ErrorInternalServerError {
        return {message: "Hello, World!"};
    }
}
